#pragma once
#include <map>
#include <string>

// Collected and described by Aquaphobic
// https://discord.gg/Gx46Zxu

struct SFlag {
    std::string Name;
    std::string Description;
};

// flag - name - description
const std::map<uint32_t, SFlag> ModelFlags{
    {0x00000001, {"IS_VAN",                     "Allows double doors for the rear doors animation."}},
    {0x00000002, {"IS_BUS",                     "Uses bus animations for entry/exit."}},
    {0x00000004, {"IS_LOW",                     "Uses animations suitable for cars with a low ride-height."}},
    {0x00000008, {"IS_BIG",                     "Changes the way that the AI drives around corners."}},
    {0x00000010, {"ABS_STD",                    "Arcade Anti-Lock Braking System (ABS) equipped as standard; minimal slip allowed."}},
    {0x00000020, {"ABS_OPTION",                 "Arcade Anti-Lock Braking System (ABS) equipped w/ brakes upgrade."}},
    {0x00000040, {"ABS_ALT_STD",                "Realistic Anti-Lock Braking System (ABS) equipped as standard; some slip allowed."}},
    {0x00000080, {"ABS_ALT_OPTION",             "Realistic Anti-Lock Braking System (ABS) equipped w/brakes upgrade."}},
    {0x00000100, {"NO_DOORS",                   "For vehicles that don't have any operable doors."}},
    {0x00000200, {"TANDEM_SEATS",               "Two people will use the front passenger seat."}},
    {0x00000400, {"SIT_IN_BOAT",                "Uses seated boat animation instead of standing."}},
    {0x00000800, {"HAS_TRACKS",                 "For vehicles with tracks instead of tires."}},
    {0x00001000, {"NO_EXHAUST",                 "Removes all exhaust particles."}},
    {0x00002000, {"DOUBLE_EXHAUST",             "Creates a second exhaust by mirroring the model's exhaust over the y-axis."}},
    {0x00004000, {"NO1FPS_LOOK_BEHIND",         "Prevents player using rear view when in first-person mode."}},
    {0x00008000, {"CAN_ENTER_IF_NO_DOOR",       "Allows entry into the vehicle despite no currently accessible doors."}},
    {0x00010000, {"AXLE_F_TORSION",             "Front wheels stay vertical to the car."}},
    {0x00020000, {"AXLE_F_SOLID",               "Front wheels stay parallel to each other."}},
    {0x00040000, {"AXLE_F_MCPHERSON",           "Front wheels can tilt."}},
    {0x00080000, {"ATTACH_PED_TO_BODYSHELL",    "???"}},
    {0x00100000, {"AXLE_R_TORSION",             "Rear wheels stay vertical to the car."}},
    {0x00200000, {"AXLE_R_SOLID",               "Rear wheels stay parallel to each other."}},
    {0x00400000, {"AXLE_R_MCPHERSON",           "Rear wheels can tilt."}},
    {0x00800000, {"DONT_FORCE_GRND_CLEARANCE",  "Bumper bones can clip through objects/terrain that are normally too high."}},
    {0x01000000, {"DONT_RENDER_STEER",          "Does not render steering animations."}},
    {0x02000000, {"NO_WHEEL_BURST",             "Has Bulletproof Tires as standard."}},
    {0x04000000, {"INDESTRUCTIBLE",             "Can't explode or be considered inoperable from damage."}},
    {0x08000000, {"DOUBLE_FRONT_WHEELS",        "Places a second instance of each front wheel next to the normal one."}},
    {0x10000000, {"RC",                         "For RC vehicles such as the RC Bandito and Invade & Persuade Tank."}},
    {0x20000000, {"DOUBLE_RWHEELS",             "Places a second instance of each rear wheel next to the normal one."}},
    {0x40000000, {"MF_NO_WHEEL_BREAK",          "Prevents wheel bones from detaching off the vehicle due to damage."}},
    {0x80000000, {"IS_HATCHBACK",               "Uses animations suitable for Trunk doors on hatchback-style vehicle bodies."}},
};

const std::map<uint32_t, SFlag> HandlingFlags{
    {0x00000001, { "SMOOTH_COMPRESN",                       "Simulates progressive spring suspension. Makes suspension compression motion smoother."}},
    {0x00000002, { "REDUCED_MOD_MASS",                      "Reduces mass added from upgrades."}},
    {0x00000004, { "_DISABLE_HORN",                         "Disables horn. Used on vehicles with KERS."}},
    {0x00000008, { "OFFROAD_ABILITY3",                      "Inverts the way grip works on the vehicle; with this flag enabled, grip starts at the fTractionCurveMin value and may increase up to the fTractionCurveMax value upon wheel slip. Grip stays at max beyond the vehicle's peak slip angle."}},
    {0x00000010, { "NO_HANDBRAKE",                          "Disables handbrake control for the vehicle."}},
    {0x00000020, { "STEER_REARWHEELS",                      "Steers the rear wheels instead of the front."}},
    {0x00000040, { "HB_REARWHEEL_STEER",                    "Handbrake control makes the rear wheels steer as well as the front."}},
    {0x00000080, { "STEER_ALL_WHEELS",                      "Steers all wheels, similar to 4-wheel-steering systems found on real vehicles. The rear wheels will steer at the same lock angle as the front, as defined by fSteeringLock."}},
    {0x00000100, { "FREEWHEEL_NO_GAS",                      "Disables engine-braking when no throttle is applied."}},
    {0x00000200, { "NO_REVERSE",                            "Disables reversing for the vehicle."}},
    {0x00000400, { "???",                                   "???"}},
    {0x00000800, { "STEER_NO_WHEELS",                       "Disables steering on all wheels, used with tracked vehicles."}},
    {0x00001000, { "CVT",                                   "Gives the vehicle a fixed-ratio transmission with a gear ratio of 0.90, used for vehicles with nInitialDriveGears=1. If gears amount to more than 1, it will simply force the vehicle into top gear upon acceleration. Recommended for electric vehicles."}},
    {0x00002000, { "ALT_EXT_WHEEL_BOUNDS_BEH",              "???"}},
    {0x00004000, { "DONT_RAISE_BOUNDS_AT_SPEED",            "???"}},
    {0x00008000, { "???",                                   "???"}},
    {0x00010000, { "LESS_SNOW_SINK",                        "Less grip loss from deep mud/snow, most notably in North Yankton."}},
    {0x00020000, { "TYRES_CAN_CLI",                         "Tires are allowed to clip into the pavement when under enough pressure, effectiveness depends on tire sidewall. Generally makes the vehicle deal with uneven terrain better. Notes: this is the reason Offroad Tires improve performance on specific vehicles made by R*."}},
    {0x00040000, { "???",                                   "???"}},
    {0x00080000, { "HEAVY_VEHICLE",                         "???"}},
    {0x00100000, { "OFFROAD_ABILITY",                       "Scaled version of 00800000; similar effects, least power."}},
    {0x00200000, { "OFFROAD_ABILITY2",                      "Scaled version of 00800000; similar effects, less power."}},
    {0x00400000, { "HF_TYRES_RAISE_SIDE_IMPACT_THRESHOLD",  "Includes the tires in the general side collision hitbox of the vehicle. Recommended for vehicles whose wheels extend beyond the bodywork, like monster-trucks."}},
    {0x00800000, { "INCREASED_GRAVITY",                     "Includes bush-collision immunity, flat grip increase proportional to slip angle/lateral velocity, increased vehicle gravity."}},
    {0x01000000, { "ENABLE_LEAN",                           "??? Notes: Possibly for motorcycle leaning or boat leaning."}},
    {0x02000000, { "_ALLOW_MOTORCYCLE_TRACTION_LOSS",       "Allows motorcycles to lose traction."}},
    {0x04000000, { "HEAVYARMOUR",                           "???"}},
    {0x08000000, { "ARMOURED",                              "???"}},
    {0x10000000, { "SELF_RIGHTING_IN_WATER",                "???"}},
    {0x20000000, { "IMPROVED_RIGHTING_FORCE",               "???"}},
    {0x40000000, { "USE_EXTRA_SOFT_SURFACE_SUS",            "???"}},
    {0x80000000, { "LAST_AVAILABLE_FLAG",                   "???"}},
};

static const std::map<uint32_t, SFlag> AdvancedFlags{
    {0x00000001, {"???",                                    "???"}},
    {0x00000002, {"???",                                    "???"}},
    {0x00000004, {"???",                                    "???"}},
    {0x00000008, {"???",                                    "???"}},
    {0x00000010, {"???",                                    "???"}},
    {0x00000020, {"???",                                    "???"}},
    {0x00000040, {"???",                                    "???"}},
    {0x00000080, {"???",                                    "???"}},
    {0x00000100, {"???",                                    "???"}},
    {0x00000200, {"???",                                    "???"}},
    {0x00000400, {"???",                                    "???"}},
    {0x00000800, {"???",                                    "???"}},
    {0x00001000, {"???",                                    "???"}},
    {0x00002000, {"???",                                    "???"}},
    {0x00004000, {"???",                                    "???"}},
    {0x00008000, {"???",                                    "???"}},
    {0x00010000, {"_TRACTION_CONTROL",                      "Earlier upshifts, hard rev-limit per gear, low-speed traction control."}},
    {0x00020000, {"_HOLD_GEAR_LONGER",                      "Later upshifts; usually hits the gear's rev limit before shifting."}},
    {0x00040000, {"_STIFFER_SPRING_SPEED",                  "Anti-downforce suspension; increases suspension spring force as vehicle goes faster."}},
    {0x00080000, {"_FAKE_WHEELSPIN",                        "Generates fake wheelspin after an instance of real wheelspin; Tyres will stabilize and show 0.0m/s of slip with debugging data, but the traction behaves like it's still spinning."}},
    {0x00100000, {"???",                                    "???"}},
    {0x00200000, {"???",                                    "???"}},
    {0x00400000, {"_SMOOTH_REV_1ST",                        "Smooth first-gear revving; resistance to hitting the rev-limit."}},
    {0x00800000, {"???",                                    "???"}},
    {0x01000000, {"???",                                    "???"}},
    {0x02000000, {"???",                                    "???"}},
    {0x04000000, {"_IGNORE_TUNED_WHEELS_CLIP",              "Forced stock-tyre clipping boundaries, the sidewall gain/loss from a custom tyre will not matter. Refer to strHandlingFlags 00020000 above."}},
    {0x08000000, {"_DOWNFORCE_KERBFIX",                     "Changes the way Downforce and spoiler tuning works, uses the setup found on Open-Wheel class vehicles in the vanilla game. Each spoiler/bumper tuning has to be given some statistics. Adjusts initial downforce from fDownforceModifier. 'Curb - boosting' seems to be nullified."}},
    {0x10000000, {"_DECREASE_BODYROLL_TUNING",              "Reduces body-roll if suspension upgrades are equipped."}},
    {0x20000000, {"???",                                    "???"}},
    {0x40000000, {"???",                                    "???"}},
    {0x80000000, {"???",                                    "???"}},
};
